name: clean_code_architecture_tdd
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.13.5
  # Local cache
  shared_preferences: ^2.0.18
  build_runner: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
 
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true